require 'test_helper'

module GraphQL
  class IDLParserInputObjectsTest < Minitest::Test
    def test_it_works_with_input_objects
      schema = File.read(File.join(RUST_FIXTURES_DIR, 'input_objects.graphql'))
      parser = GraphQL::IDLParser.new(schema: schema)
      types = parser.process.types

      assert_equal types[0][:typename], 'input_object'
      assert_equal 'UpdateTopicsInput', types[0][:name]
      assert_equal 'Autogenerated input type of UpdateTopics', types[0][:description]
      assert_equal 3, types[0][:fields].count
      assert_equal 'clientMutationId', types[0][:fields][0][:name]
      assert_equal 'A unique identifier for the client performing the mutation.', types[0][:fields][0][:description]
      assert_equal 'String', types[0][:fields][0][:type_info][:name]
      assert_equal '', types[0][:fields][0][:type_info][:info]
      assert_equal 'repositoryId', types[0][:fields][1][:name]
      assert_equal 'The Node ID of the repository.', types[0][:fields][1][:description]
      assert_equal 'ID', types[0][:fields][1][:type_info][:name]
      assert_equal '!', types[0][:fields][1][:type_info][:info]
      assert_equal 'topicNames', types[0][:fields][2][:name]
      assert_equal 'An array of topic names.', types[0][:fields][2][:description]
      assert_equal 'String', types[0][:fields][2][:type_info][:name]
      assert_equal '[!]!', types[0][:fields][2][:type_info][:info]
    end
  end
end
