#!/bin/bash

set -e

if [ -z "$1" ]; then
  BRANCH="master"
else
  BRANCH=$1
fi

echo "Using $BRANCH..."

echo "Checking out graphql-idl-parser"
echo "---------------------"
cd ext/graphql-idl-parser/graphql-idl-parser
git fetch origin
git checkout $BRANCH && git pull
sha=`git rev-parse HEAD`
cd ../../..
git add ext/graphql-idl-parser/graphql-idl-parser
git commit -m "Update graphql-idl-parser to $(git config submodule.ext/graphql-idl-parser/graphql-idl-parser.url | sed s_.git\$__)/commit/${sha}"
